# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roy's Corner
email: chanonroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Front End Developer and Semi-Pro Gamer. You may recognize me from my brief appearance as a blurred face on Google Street View.
  I like to teach myself new things in my spare time.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://blog.chanonroy.com" # the base hostname & protocol for your site
twitter_username: chanonroy
github_username:  chanonroy
gems: [jekyll-paginate]
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Chanon Roy
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
